"""empty message

Revision ID: 2c2c956842b0
Revises: 6ce7b8881c0b
Create Date: 2023-05-09 10:19:48.172143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2c956842b0'
down_revision = '6ce7b8881c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crystal', sa.Column('healer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crystal', 'healer', ['healer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crystal', type_='foreignkey')
    op.drop_column('crystal', 'healer_id')
    # ### end Alembic commands ###
